import Hike from "./hike";

export const HIKES: Hike[] = [
  {
    id: 1,
    title: "Le plateau de La Molière depuis Engins",
    summary: "",
    massif: "Vercors",
    activity: "Randonnée pédestre",
    made_at: "Engins, Isère, France",
    distance: "12.48 km",
    duration: "",
    type: "Boucle",
    done_with: "Accompagné",
    comment: "",
    relive_link: "",
    created: new Date(),
  },
  {
    id: 2,
    title: "La Grande Sure par le Cul de la Lampe, depuis St-Laurent-du-Pont",
    summary: "",
    massif: "Chartreuse",
    activity: "Randonnée pédestre",
    made_at: "St-Laurent-du-Pont, Isère, France",
    distance: "20,25 km",
    duration: "",
    type: "Aller-retour",
    done_with: "Accompagné",
    comment: "",
    relive_link: "https://www.relive.cc/view/vdvmKpkJAx6",
    created: new Date(),
  },
  {
    id: 3,
    title:
      "Mont St-Eynard par la crête du Rocher du Bret, depuis Le Sappey-en-Chartreuse",
    summary: "",
    massif: "Chartreuse",
    activity: "Randonnée pédestre",
    made_at: "Le Sappey-en-Chartreuse, Isère, France",
    distance: "8,19 km",
    duration: "",
    type: "Boucle",
    done_with: "Seul",
    comment: "",
    relive_link: "https://www.relive.cc/view/vYvrL7gKMx6",
    created: new Date(),
  },
  {
    id: 4,
    title: "Le Pic Saint-Michel par le Col de l'Arc",
    summary: "",
    massif: "Vercors",
    activity: "Randonnée pédestre",
    made_at: "Lans-en-Vercors, Isère, France",
    distance: "8,65 km",
    duration: "",
    type: "Boucle",
    done_with: "Accompagné",
    comment: "",
    relive_link: "https://www.relive.cc/view/vPv4eDpJx3O",
    created: new Date(),
  },
];

export default HIKES;
