import Hike from "./hike";

export const HIKES: Hike[] = [
  {
    id: 1,
    title: "Le plateau de La Molière depuis Engins",
    picture:
      "https://www.trekmag.com/media/news/2013/11/Aguila-CHARTREUSE-(6).jpg",
    summary: "",
    massif: "Vercors",
    activity: "Randonnée pédestre",
    made_at: "Engins, Isère, France",
    distance: "12.48 km",
    duration: "",
    type: "Boucle",
    done_with: "Accompagné",
    comment: "",
    relive_link: "",
    created: new Date(),
  },
  {
    id: 2,
    title: "La Grande Sure par le Cul de la Lampe, depuis St-Laurent-du-Pont",
    picture:
      "https://www.trekmag.com/media/news/2013/11/Aguila-CHARTREUSE-(6).jpg",
    summary: "",
    massif: "Chartreuse",
    activity: "Randonnée pédestre",
    made_at: "St-Laurent-du-Pont, Isère, France",
    distance: "20,25 km",
    duration: "",
    type: "Aller-retour",
    done_with: "Accompagné",
    comment: "",
    relive_link: "https://www.relive.cc/view/vdvmKpkJAx6",
    created: new Date(),
  },
  {
    id: 3,
    title:
      "Mont St-Eynard par la crête du Rocher du Bret, depuis Le Sappey-en-Chartreuse",
    picture:
      "https://www.trekmag.com/media/news/2013/11/Aguila-CHARTREUSE-(6).jpg",
    summary: "",
    massif: "Chartreuse",
    activity: "Randonnée pédestre",
    made_at: "Le Sappey-en-Chartreuse, Isère, France",
    distance: "8,19 km",
    duration: "",
    type: "Boucle",
    done_with: "Seul",
    comment: "",
    relive_link: "https://www.relive.cc/view/vYvrL7gKMx6",
    created: new Date(),
  },
  {
    id: 4,
    title: "Le Pic Saint-Michel par le Col de l'Arc",
    picture:
      "https://www.trekmag.com/media/news/2013/11/Aguila-CHARTREUSE-(6).jpg",
    summary: "",
    massif: "Vercors",
    activity: "Randonnée pédestre",
    made_at: "Lans-en-Vercors, Isère, France",
    distance: "8,65 km",
    duration: "",
    type: "Boucle",
    done_with: "Accompagné",
    comment: "",
    relive_link: "https://www.relive.cc/view/vPv4eDpJx3O",
    created: new Date(),
  },
  {
    id: 5,
    title: "Le Mont Joigny par la Pointe du Gorgeat",
    picture:
      "https://www.trekmag.com/media/news/2013/11/Aguila-CHARTREUSE-(6).jpg",
    summary: "",
    massif: "Chartreuse",
    activity: "Randonnée pédestre",
    made_at: "Apremont, Isère, France",
    distance: "7,15 km",
    duration: "",
    type: "Boucle",
    done_with: "Accompagné",
    comment: "",
    relive_link: "https://www.relive.cc/view/vJOKpPnkew6",
    created: new Date(),
  },
  {
    id: 6,
    title: "Une nuit dans les Ecrins au refuge de Chabournéou",
    picture:
      "https://www.trekmag.com/media/news/2013/11/Aguila-CHARTREUSE-(6).jpg",
    summary: "",
    massif: "Ecrins",
    activity: "Randonnée pédestre",
    made_at: "La Chapelle-en-Valgaudémar, Hautes-Alpes, France",
    distance: "17,67 km",
    duration: "",
    type: "Boucle trek",
    done_with: "Accompagné",
    comment: "",
    relive_link: "https://www.relive.cc/view/vDqgMQr8pVO",
    created: new Date(),
  },
  {
    id: 7,
    title: "Le Grammont par le Col et le lac de Taney",
    picture:
      "https://www.trekmag.com/media/news/2013/11/Aguila-CHARTREUSE-(6).jpg",
    summary: "",
    massif: "Chablais valaisan",
    activity: "Randonnée pédestre",
    made_at: "Tanay, Valais, Suisse",
    distance: "15,25 km",
    duration: "",
    type: "Boucle",
    done_with: "Seul",
    comment: "",
    relive_link: "https://www.relive.cc/view/vDqgMPpnEVO",
    created: new Date(),
  },
  {
    id: 8,
    title: "Lac Salanfe et col d'Emaney",
    picture:
      "https://www.trekmag.com/media/news/2013/11/Aguila-CHARTREUSE-(6).jpg",
    summary: "",
    massif: "Chablais valaisan",
    activity: "Randonnée pédestre",
    made_at: "Le Salantin, Valais, Suisse",
    distance: "19,27 km",
    duration: "",
    type: "Boucle",
    done_with: "Seul",
    comment: "",
    relive_link: "",
    created: new Date(),
  },
  {
    id: 9,
    title: "Traces de dinosaures aux lacs Emosson",
    picture:
      "https://www.trekmag.com/media/news/2013/11/Aguila-CHARTREUSE-(6).jpg",
    summary: "",
    massif: "Chablais valaisan",
    activity: "Randonnée pédestre",
    made_at: "Les Creusiers, Valais, Suisse",
    distance: "15,70 km",
    duration: "",
    type: "Boucle",
    done_with: "Seul",
    comment: "",
    relive_link: "",
    created: new Date(),
  },
  {
    id: 10,
    title: "Le Grand Som par la combe des Eparres",
    picture:
      "https://www.trekmag.com/media/news/2013/11/Aguila-CHARTREUSE-(6).jpg",
    summary: "",
    massif: "Chartreuse",
    activity: "Randonnée pédestre",
    made_at: "Corbel, Isère, France",
    distance: "11,33 km",
    duration: "",
    type: "Aller-retour",
    done_with: "Accompagné",
    comment: "",
    relive_link: "",
    created: new Date(),
  },
  {
    id: 11,
    title:
      "Les rochers de la Balme et la tete des Chaudieres, par la Cabane de Carette",
    picture:
      "https://www.trekmag.com/media/news/2013/11/Aguila-CHARTREUSE-(6).jpg",
    summary: "",
    massif: "Vercors",
    activity: "Randonnée pédestre",
    made_at: "Corrençon-en-Vercors, Isère, France",
    distance: "16,12 km",
    duration: "",
    type: "Boucle",
    done_with: "Accompagné",
    comment: "",
    relive_link: "",
    created: new Date(),
  },
];

export default HIKES;
